/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FileId = IDL.Text;
export const DeleteResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileCategory = IDL.Variant({
  'audio' : IDL.Null,
  'video' : IDL.Null,
  'document' : IDL.Null,
  'image' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const FileMetadata = IDL.Record({
  'id' : FileId,
  'name' : IDL.Text,
  'mimeType' : IDL.Text,
  'fileSize' : IDL.Nat,
  'category' : FileCategory,
  'uploadedAt' : Timestamp,
});
export const StorageStats = IDL.Record({
  'totalFiles' : IDL.Nat,
  'videoCount' : IDL.Nat,
  'imageCount' : IDL.Nat,
  'totalBytes' : IDL.Nat,
  'audioCount' : IDL.Nat,
  'documentCount' : IDL.Nat,
});
export const SortField = IDL.Variant({
  'name' : IDL.Null,
  'fileSize' : IDL.Null,
  'uploadDate' : IDL.Null,
});
export const SortOrder = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
export const ListFilesRequest = IDL.Record({
  'sortField' : SortField,
  'sortOrder' : SortOrder,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'category' : IDL.Opt(FileCategory),
  'searchQuery' : IDL.Opt(IDL.Text),
});
export const ListFilesResponse = IDL.Record({
  'files' : IDL.Vec(FileMetadata),
  'page' : IDL.Nat,
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
});
export const RenameResult = IDL.Variant({
  'ok' : FileMetadata,
  'err' : IDL.Text,
});
export const UploadResult = IDL.Variant({
  'ok' : FileMetadata,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'deleteFile' : IDL.Func([FileId], [DeleteResult], []),
  'getFileBlob' : IDL.Func([FileId], [IDL.Opt(ExternalBlob)], ['query']),
  'getFileMetadata' : IDL.Func([FileId], [IDL.Opt(FileMetadata)], ['query']),
  'getStorageStats' : IDL.Func([], [StorageStats], ['query']),
  'listFiles' : IDL.Func([ListFilesRequest], [ListFilesResponse], ['query']),
  'renameFile' : IDL.Func([FileId, IDL.Text], [RenameResult], []),
  'uploadFile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [UploadResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FileId = IDL.Text;
  const DeleteResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileCategory = IDL.Variant({
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'document' : IDL.Null,
    'image' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const FileMetadata = IDL.Record({
    'id' : FileId,
    'name' : IDL.Text,
    'mimeType' : IDL.Text,
    'fileSize' : IDL.Nat,
    'category' : FileCategory,
    'uploadedAt' : Timestamp,
  });
  const StorageStats = IDL.Record({
    'totalFiles' : IDL.Nat,
    'videoCount' : IDL.Nat,
    'imageCount' : IDL.Nat,
    'totalBytes' : IDL.Nat,
    'audioCount' : IDL.Nat,
    'documentCount' : IDL.Nat,
  });
  const SortField = IDL.Variant({
    'name' : IDL.Null,
    'fileSize' : IDL.Null,
    'uploadDate' : IDL.Null,
  });
  const SortOrder = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
  const ListFilesRequest = IDL.Record({
    'sortField' : SortField,
    'sortOrder' : SortOrder,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'category' : IDL.Opt(FileCategory),
    'searchQuery' : IDL.Opt(IDL.Text),
  });
  const ListFilesResponse = IDL.Record({
    'files' : IDL.Vec(FileMetadata),
    'page' : IDL.Nat,
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
  });
  const RenameResult = IDL.Variant({ 'ok' : FileMetadata, 'err' : IDL.Text });
  const UploadResult = IDL.Variant({ 'ok' : FileMetadata, 'err' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'deleteFile' : IDL.Func([FileId], [DeleteResult], []),
    'getFileBlob' : IDL.Func([FileId], [IDL.Opt(ExternalBlob)], ['query']),
    'getFileMetadata' : IDL.Func([FileId], [IDL.Opt(FileMetadata)], ['query']),
    'getStorageStats' : IDL.Func([], [StorageStats], ['query']),
    'listFiles' : IDL.Func([ListFilesRequest], [ListFilesResponse], ['query']),
    'renameFile' : IDL.Func([FileId, IDL.Text], [RenameResult], []),
    'uploadFile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [UploadResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };