/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DeleteResult = { 'ok' : null } |
  { 'err' : string };
export type ExternalBlob = Uint8Array;
export type FileCategory = { 'audio' : null } |
  { 'video' : null } |
  { 'document' : null } |
  { 'image' : null };
export type FileId = string;
export interface FileMetadata {
  'id' : FileId,
  'name' : string,
  'mimeType' : string,
  'fileSize' : bigint,
  'category' : FileCategory,
  'uploadedAt' : Timestamp,
}
export interface ListFilesRequest {
  'sortField' : SortField,
  'sortOrder' : SortOrder,
  'page' : bigint,
  'pageSize' : bigint,
  'category' : [] | [FileCategory],
  'searchQuery' : [] | [string],
}
export interface ListFilesResponse {
  'files' : Array<FileMetadata>,
  'page' : bigint,
  'totalCount' : bigint,
  'pageSize' : bigint,
}
export type RenameResult = { 'ok' : FileMetadata } |
  { 'err' : string };
export type SortField = { 'name' : null } |
  { 'fileSize' : null } |
  { 'uploadDate' : null };
export type SortOrder = { 'asc' : null } |
  { 'desc' : null };
export interface StorageStats {
  'totalFiles' : bigint,
  'videoCount' : bigint,
  'imageCount' : bigint,
  'totalBytes' : bigint,
  'audioCount' : bigint,
  'documentCount' : bigint,
}
export type Timestamp = bigint;
export type UploadResult = { 'ok' : FileMetadata } |
  { 'err' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'deleteFile' : ActorMethod<[FileId], DeleteResult>,
  'getFileMetadata' : ActorMethod<[FileId], [] | [FileMetadata]>,
  'getStorageStats' : ActorMethod<[], StorageStats>,
  'listFiles' : ActorMethod<[ListFilesRequest], ListFilesResponse>,
  'renameFile' : ActorMethod<[FileId, string], RenameResult>,
  'uploadFile' : ActorMethod<
    [string, string, bigint, ExternalBlob],
    UploadResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];