/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type RenameResult = {
    __kind__: "ok";
    ok: FileMetadata;
} | {
    __kind__: "err";
    err: string;
};
export type Timestamp = bigint;
export interface FileMetadata {
    id: FileId;
    name: string;
    mimeType: string;
    fileSize: bigint;
    category: FileCategory;
    uploadedAt: Timestamp;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type DeleteResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type UploadResult = {
    __kind__: "ok";
    ok: FileMetadata;
} | {
    __kind__: "err";
    err: string;
};
export interface ListFilesRequest {
    sortField: SortField;
    sortOrder: SortOrder;
    page: bigint;
    pageSize: bigint;
    category?: FileCategory;
    searchQuery?: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ListFilesResponse {
    files: Array<FileMetadata>;
    page: bigint;
    totalCount: bigint;
    pageSize: bigint;
}
export type FileId = string;
export interface StorageStats {
    totalFiles: bigint;
    videoCount: bigint;
    imageCount: bigint;
    totalBytes: bigint;
    audioCount: bigint;
    documentCount: bigint;
}
export enum FileCategory {
    audio = "audio",
    video = "video",
    document_ = "document",
    image = "image"
}
export enum SortField {
    name = "name",
    fileSize = "fileSize",
    uploadDate = "uploadDate"
}
export enum SortOrder {
    asc = "asc",
    desc = "desc"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    deleteFile(fileId: FileId): Promise<DeleteResult>;
    getFileBlob(fileId: FileId): Promise<ExternalBlob | null>;
    getFileMetadata(fileId: FileId): Promise<FileMetadata | null>;
    getStorageStats(): Promise<StorageStats>;
    listFiles(request: ListFilesRequest): Promise<ListFilesResponse>;
    renameFile(fileId: FileId, newName: string): Promise<RenameResult>;
    uploadFile(name: string, mimeType: string, fileSize: bigint, blob: ExternalBlob): Promise<UploadResult>;
}
import type { DeleteResult as _DeleteResult, ExternalBlob as _ExternalBlob, FileCategory as _FileCategory, FileId as _FileId, FileMetadata as _FileMetadata, ListFilesRequest as _ListFilesRequest, ListFilesResponse as _ListFilesResponse, RenameResult as _RenameResult, SortField as _SortField, SortOrder as _SortOrder, Timestamp as _Timestamp, UploadResult as _UploadResult, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async deleteFile(arg0: FileId): Promise<DeleteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFile(arg0);
                return from_candid_DeleteResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFile(arg0);
            return from_candid_DeleteResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFileBlob(arg0: FileId): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileBlob(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileBlob(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFileMetadata(arg0: FileId): Promise<FileMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileMetadata(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileMetadata(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStorageStats(): Promise<StorageStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStorageStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStorageStats();
            return result;
        }
    }
    async listFiles(arg0: ListFilesRequest): Promise<ListFilesResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.listFiles(to_candid_ListFilesRequest_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ListFilesResponse_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFiles(to_candid_ListFilesRequest_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ListFilesResponse_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameFile(arg0: FileId, arg1: string): Promise<RenameResult> {
        if (this.processError) {
            try {
                const result = await this.actor.renameFile(arg0, arg1);
                return from_candid_RenameResult_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameFile(arg0, arg1);
            return from_candid_RenameResult_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadFile(arg0: string, arg1: string, arg2: bigint, arg3: ExternalBlob): Promise<UploadResult> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFile(arg0, arg1, arg2, await to_candid_ExternalBlob_n30(this._uploadFile, this._downloadFile, arg3));
                return from_candid_UploadResult_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFile(arg0, arg1, arg2, await to_candid_ExternalBlob_n30(this._uploadFile, this._downloadFile, arg3));
            return from_candid_UploadResult_n31(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DeleteResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeleteResult): DeleteResult {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FileCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileCategory): FileCategory {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_FileMetadata_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileMetadata): FileMetadata {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ListFilesResponse_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListFilesResponse): ListFilesResponse {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_RenameResult_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RenameResult): RenameResult {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UploadResult_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UploadResult): UploadResult {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileMetadata]): FileMetadata | null {
    return value.length === 0 ? null : from_candid_FileMetadata_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FileId;
    name: string;
    mimeType: string;
    fileSize: bigint;
    category: _FileCategory;
    uploadedAt: _Timestamp;
}): {
    id: FileId;
    name: string;
    mimeType: string;
    fileSize: bigint;
    category: FileCategory;
    uploadedAt: Timestamp;
} {
    return {
        id: value.id,
        name: value.name,
        mimeType: value.mimeType,
        fileSize: value.fileSize,
        category: from_candid_FileCategory_n15(_uploadFile, _downloadFile, value.category),
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    files: Array<_FileMetadata>;
    page: bigint;
    totalCount: bigint;
    pageSize: bigint;
}): {
    files: Array<FileMetadata>;
    page: bigint;
    totalCount: bigint;
    pageSize: bigint;
} {
    return {
        files: from_candid_vec_n27(_uploadFile, _downloadFile, value.files),
        page: value.page,
        totalCount: value.totalCount,
        pageSize: value.pageSize
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    audio: null;
} | {
    video: null;
} | {
    document: null;
} | {
    image: null;
}): FileCategory {
    return "audio" in value ? FileCategory.audio : "video" in value ? FileCategory.video : "document" in value ? FileCategory.document : "image" in value ? FileCategory.image : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _FileMetadata;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: FileMetadata;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_FileMetadata_n13(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileMetadata>): Array<FileMetadata> {
    return value.map((x)=>from_candid_FileMetadata_n13(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FileCategory_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileCategory): _FileCategory {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_ListFilesRequest_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListFilesRequest): _ListFilesRequest {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_SortField_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortField): _SortField {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_SortOrder_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): _SortOrder {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sortField: SortField;
    sortOrder: SortOrder;
    page: bigint;
    pageSize: bigint;
    category?: FileCategory;
    searchQuery?: string;
}): {
    sortField: _SortField;
    sortOrder: _SortOrder;
    page: bigint;
    pageSize: bigint;
    category: [] | [_FileCategory];
    searchQuery: [] | [string];
} {
    return {
        sortField: to_candid_SortField_n19(_uploadFile, _downloadFile, value.sortField),
        sortOrder: to_candid_SortOrder_n21(_uploadFile, _downloadFile, value.sortOrder),
        page: value.page,
        pageSize: value.pageSize,
        category: value.category ? candid_some(to_candid_FileCategory_n23(_uploadFile, _downloadFile, value.category)) : candid_none(),
        searchQuery: value.searchQuery ? candid_some(value.searchQuery) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortField): {
    name: null;
} | {
    fileSize: null;
} | {
    uploadDate: null;
} {
    return value == SortField.name ? {
        name: null
    } : value == SortField.fileSize ? {
        fileSize: null
    } : value == SortField.uploadDate ? {
        uploadDate: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): {
    asc: null;
} | {
    desc: null;
} {
    return value == SortOrder.asc ? {
        asc: null
    } : value == SortOrder.desc ? {
        desc: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileCategory): {
    audio: null;
} | {
    video: null;
} | {
    document: null;
} | {
    image: null;
} {
    return value == FileCategory.audio ? {
        audio: null
    } : value == FileCategory.video ? {
        video: null
    } : value == FileCategory.document ? {
        document_: null
    } : value == FileCategory.image ? {
        image: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
